# Generated by Django 5.0.1 on 2024-10-12 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Add any dependencies here if necessary
        # For example, if you have a migration for existing models
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('account_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('admin_id', models.BigIntegerField(blank=True, null=True)),
                ('account_name', models.CharField(max_length=255)),
                ('status', models.CharField(default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
