# Generated by Django 5.1.2 on 2024-10-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('parameter_id', models.CharField(primary_key=True, serialize=False)),
                ('parameter_name', models.CharField(max_length=255)),
                ('data_type', models.CharField(max_length=50, null=True)),
                ('default_value', models.CharField(max_length=255, null=True)),
                ('min_value', models.CharField(max_length=255, null=True)),
                ('max_value', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'parameters',
            },
        ),
    ]
